dist: xenial

language: python

services:
  - mongodb

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py27-mg35
    python: 2.7
  - env: TOX_ENV=py35-mg35
    python: 3.5
  - env: TOX_ENV=py36-mg35
    python: 3.6

  - env: TOX_ENV=py27-mg3x
    python: 2.7
  - env: TOX_ENV=py35-mg3x
    python: 3.5
  - env: TOX_ENV=py36-mg3x
    python: 3.6

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

install:
  - echo

script: travis_retry tox -e $TOX_ENV
